<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>Input.Interception</AssemblyName>
    <RootNamespace>Input.Interception</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Input.Abstractions\Input.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="native\interception.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>

</Project>
