<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64</Platforms>
    <AssemblyName>Input.Native</AssemblyName>
    <RootNamespace>Input.Native</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Input.Abstractions\Input.Abstractions.csproj" />
  </ItemGroup>

</Project>
