<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF> 
	<PlatformTarget>x64</PlatformTarget> 
	<Platforms>AnyCPU;x64</Platforms>
    <AssemblyName>Vision.RegionEditor</AssemblyName>
    <RootNamespace>Vision.RegionEditor</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Vision.GameCapture\Vision.GameCapture.csproj" />
  </ItemGroup>

</Project>
